import { View } from "react-native";
import { useTranslation } from "react-i18next";
import { AlertCard } from "@/components/patterns/alert-card";
import { ComparisonCard, type ComparisonChange } from "@/components/patterns/comparison-card";
import { Button } from "@/components/primitives/button";
import { getPurchaseOrderReference, type PurchaseOrderConflictChange, type PurchaseOrderConflictType, type PurchaseOrderRecord } from "@/features/purchasing";
import { useAppTheme } from "@/theme/ThemeProvider";
export type PurchaseOrderConflictAlertProps = { accessibilityLabel?: string; changes?: PurchaseOrderConflictChange[]; compact?: boolean; conflictType: PurchaseOrderConflictType; localPurchaseOrder: PurchaseOrderRecord; onDiscardLocal?: () => void; onReload: () => void; onRetry?: () => void; onReview?: () => void; remotePurchaseOrder?: PurchaseOrderRecord | null; };
function getConflictDescriptionKey(type: PurchaseOrderConflictType) { if (type === "optimistic_lock") return "purchasing.conflicts.optimisticLock"; if (type === "status_changed") return "purchasing.conflicts.statusChanged"; if (type === "receiving_changed") return "purchasing.conflicts.receivingChanged"; return "purchasing.conflicts.updated"; }
export function PurchaseOrderConflictAlert({ accessibilityLabel, changes = [], compact = false, conflictType, localPurchaseOrder, onDiscardLocal, onReload, onRetry, onReview, remotePurchaseOrder }: PurchaseOrderConflictAlertProps) { const { t } = useTranslation("common"); const { theme } = useAppTheme(); const reference = getPurchaseOrderReference(remotePurchaseOrder ?? localPurchaseOrder) ?? t("purchasing.conflicts.purchaseOrderFallback"); const comparisonChanges: ComparisonChange[] = changes.map((change, index) => ({ id: change.id ?? `conflict-${index}`, label: change.label ?? (change.translationKey ? t(change.translationKey) : t("purchasing.conflicts.changedField")), before: change.before, after: change.after })); return <View accessibilityLabel={accessibilityLabel ?? t("purchasing.conflicts.accessibilityLabel", { reference })} style={{ gap: theme.spacing[3] }}><AlertCard description={t(getConflictDescriptionKey(conflictType), { reference })} title={t("purchasing.conflicts.title")} tone="warning" />{!compact && comparisonChanges.length ? <ComparisonCard changes={comparisonChanges} subtitle={t("purchasing.conflicts.reviewDescription")} title={t("purchasing.conflicts.reviewTitle")} variant="muted" /> : null}<View style={{ flexDirection: "row", flexWrap: "wrap", gap: theme.spacing[2] }}><Button label={t("purchasing.conflicts.reloadLatest")} onPress={onReload} variant="primary" />{onReview ? <Button label={t("purchasing.conflicts.reviewChanges")} onPress={onReview} variant="secondary" /> : null}{onDiscardLocal ? <Button label={t("purchasing.conflicts.discardLocal")} onPress={onDiscardLocal} variant="ghost" /> : null}{onRetry ? <Button label={t("purchasing.conflicts.retry")} onPress={onRetry} variant="ghost" /> : null}</View></View>; }
