import { View } from "react-native";
import { useTranslation } from "react-i18next";
import { AlertCard } from "@/components/patterns/alert-card";
import { ListCard, type ListCardItem } from "@/components/patterns/list-card";
import { Badge } from "@/components/primitives/badge";
import { Text } from "@/components/primitives/text";
import { formatDecimalCurrency, formatPurchasingDateLabel, getPriceTrend, getSupplierItemName, type PriceHistoryRecord, type SupplierItemRecord, type SupplierRecord } from "@/features/purchasing";
import { useAppTheme } from "@/theme/ThemeProvider";
export type SupplierPriceHistoryProps = { accessibilityLabel?: string; compact?: boolean; currency?: string | null; error?: string | null; loading?: boolean; maxEntries?: number; priceHistory: PriceHistoryRecord[]; supplier?: SupplierRecord | null; supplierItem?: SupplierItemRecord | null; };
export function SupplierPriceHistory({ accessibilityLabel, compact = false, currency, error, loading = false, maxEntries, priceHistory, supplierItem }: SupplierPriceHistoryProps) { const { t, i18n } = useTranslation("common"); const { theme } = useAppTheme(); if (error) return <AlertCard description={error} title={t("purchasing.priceHistory.errorTitle")} tone="warning" />; const sortedEntries=[...priceHistory].sort((a,b)=>(b.effectiveAt?Date.parse(b.effectiveAt):0)-(a.effectiveAt?Date.parse(a.effectiveAt):0)); const entries=typeof maxEntries==="number"?sortedEntries.slice(0,maxEntries):sortedEntries; const currentPriceLabel=formatDecimalCurrency(supplierItem?.price,supplierItem?.currency??currency,i18n.language); const listItems:ListCardItem[]=entries.map((entry,index)=>{const previous=entries[index+1];const sameCurrency=!previous||previous.currency===entry.currency;const trend=sameCurrency?getPriceTrend(entry.price,previous?.price):"unknown";const priceLabel=formatDecimalCurrency(entry.price,entry.currency??currency,i18n.language);const previousLabel=sameCurrency?formatDecimalCurrency(previous?.price,previous?.currency??currency,i18n.language):null;const dateLabel=formatPurchasingDateLabel(entry.effectiveAt,i18n.language);return{id:entry.id??`price-${index}`,title:priceLabel??t("purchasing.priceHistory.unknownPrice"),subtitle:<View style={{gap:theme.spacing[1]}}>{dateLabel?<Text tone="muted" variant="bodySmall">{dateLabel}</Text>:null}{!compact&&previousLabel?<Text tone="muted" variant="bodySmall">{t("purchasing.priceHistory.previousPrice",{value:previousLabel})}</Text>:null}</View>,trailing:trend==="increased"||trend==="decreased"?<Badge label={t(trend==="increased"?"purchasing.priceHistory.increased":"purchasing.priceHistory.decreased")} size="sm" variant="neutral" />:undefined};}); return <View accessibilityLabel={accessibilityLabel??t("purchasing.priceHistory.accessibilityLabel")} style={{gap:theme.spacing[3]}}>{currentPriceLabel?<View style={{gap:theme.spacing[1]}}><Text tone="muted" variant="caption">{t("purchasing.priceHistory.currentPrice")}</Text><Text selectable variant="h4">{currentPriceLabel}</Text></View>:null}<ListCard emptyContent={<Text tone="muted" variant="bodySmall">{loading?t("purchasing.priceHistory.loading"):t("purchasing.priceHistory.empty")}</Text>} items={listItems} subtitle={getSupplierItemName(supplierItem)??undefined} title={t("purchasing.priceHistory.title")} variant={compact?"muted":"default"} /></View>; }
