<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('idempotency_keys', function (Blueprint $table) {
            $table->ulid('id')->primary();

            $table->foreignUlid('workspace_id')
                ->constrained('workspaces')
                ->cascadeOnDelete();

            $table->foreignUlid('user_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete();

            /*
    |--------------------------------------------------------------------------
    | Idempotency key
    |--------------------------------------------------------------------------
    |
    | Generated by the client.
    | Example:
    | 550e8400-e29b-41d4-a716-446655440000
    */
            $table->string('key', 120);

            /*
    |--------------------------------------------------------------------------
    | Action
    |--------------------------------------------------------------------------
    |
    | Examples:
    | prep_items.complete
    | prep_lists.create
    | purchase_orders.submit
    | confirmations.execute
    | events.create
    */
            $table->string('action', 120);

            /*
    |--------------------------------------------------------------------------
    | Request identity
    |--------------------------------------------------------------------------
    |
    | Hash of the normalized request payload.
    |
    | Prevents a client from accidentally reusing the same idempotency key
    | with a different payload.
    */
            $table->string('request_hash', 128);

            /*
    |--------------------------------------------------------------------------
    | Processing state
    |--------------------------------------------------------------------------
    */
            $table->enum('status', [
                'processing',
                'completed',
                'failed',
            ])->default('processing');

            /*
    |--------------------------------------------------------------------------
    | Response
    |--------------------------------------------------------------------------
    */
            $table->unsignedSmallInteger('response_status')
                ->nullable();

            /*
    |--------------------------------------------------------------------------
    | Response snapshot
    |--------------------------------------------------------------------------
    |
    | Store only what is necessary to safely replay the response.
    | Avoid large/sensitive payloads.
    */
            $table->json('response_json')
                ->nullable();

            /*
    |--------------------------------------------------------------------------
    | Result reference
    |--------------------------------------------------------------------------
    |
    | Prefer stable references where possible.
    |
    | Example:
    | {
    |   "type": "prep_list",
    |   "id": "01..."
    | }
    */
            $table->json('result_ref_json')
                ->nullable();

            /*
    |--------------------------------------------------------------------------
    | Error
    |--------------------------------------------------------------------------
    */
            $table->string('error_code', 100)
                ->nullable();

            $table->text('error_message')
                ->nullable();

            /*
    |--------------------------------------------------------------------------
    | Processing timestamps
    |--------------------------------------------------------------------------
    */
            $table->timestamp('started_at')
                ->nullable();

            $table->timestamp('completed_at')
                ->nullable();

            /*
    |--------------------------------------------------------------------------
    | Expiration
    |--------------------------------------------------------------------------
    |
    | Allows old keys to be cleaned periodically.
    */
            $table->timestamp('expires_at');

            /*
    |--------------------------------------------------------------------------
    | Correlation
    |--------------------------------------------------------------------------
    |
    | Useful for tracing API -> action -> job -> audit/AI.
    */
            $table->ulid('correlation_id')
                ->nullable();

            /*
    |--------------------------------------------------------------------------
    | Metadata
    |--------------------------------------------------------------------------
    */
            $table->json('metadata')
                ->nullable();

            $table->timestamps();

            /*
    |--------------------------------------------------------------------------
    | Uniqueness
    |--------------------------------------------------------------------------
    |
    | Same key cannot be reused inside the same workspace.
    */
            $table->unique([
                'workspace_id',
                'key',
            ]);

            /*
    |--------------------------------------------------------------------------
    | Indexes
    |--------------------------------------------------------------------------
    */
            $table->index([
                'workspace_id',
                'action',
                'created_at',
            ]);

            $table->index([
                'workspace_id',
                'status',
                'expires_at',
            ]);

            $table->index([
                'user_id',
                'created_at',
            ]);

            $table->index('correlation_id');

            $table->index('expires_at');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('idempotency_keys');
    }
};
