import type { Href } from "expo-router";

export const routes = {
  app: {
    calendar: "/(app)/calendar" as Href,
    billing: "/(app)/billing" as Href,
    chat: "/(app)/chat" as Href,
    clientCreate: "/(app)/clients/create" as Href,
    clientDetail: "/(app)/clients/[id]" as Href,
    clientEdit: "/(app)/clients/[id]/edit" as Href,
    clients: "/(app)/clients" as Href,
    audit: "/(app)/audit" as Href,
    contactCreate: "/(app)/contacts/create" as Href,
    contactEdit: "/(app)/contacts/[id]/edit" as Href,
    contacts: "/(app)/contacts" as Href,
    documentChangeReview: "/(app)/documents/[documentId]/changes" as Href,
    documentDetail: "/(app)/documents/[documentId]" as Href,
    documentReview: "/(app)/documents/[documentId]/review" as Href,
    documentUpload: "/(app)/documents/upload" as Href,
    documentVersions: "/(app)/documents/[documentId]/versions" as Href,
    documents: "/(app)/documents" as Href,
    eventCalendar: "/(app)/events/calendar" as Href,
    eventCreate: "/(app)/events/new" as Href,
    eventDetail: "/(app)/events/[eventId]" as Href,
    eventEdit: "/(app)/events/[eventId]/edit" as Href,
    events: "/(app)/events" as Href,
    index: "/(app)" as Href,
    availability: "/(app)/availability" as Href,
    menuCreate: "/(app)/menus/new" as Href,
    menuDetail: "/(app)/menus/[menuId]" as Href,
    menuEdit: "/(app)/menus/[menuId]/edit" as Href,
    menus: "/(app)/menus" as Href,
    operations: "/(app)/operations" as Href,
    prep: "/(app)/prep" as Href,
    prepDetail: "/(app)/prep/[prepListId]" as Href,
    prepGenerate: "/(app)/prep/generate" as Href,
    profile: "/(app)/profile" as Href,
    recipeCreate: "/(app)/recipes/new" as Href,
    recipeDetail: "/(app)/recipes/[recipeId]" as Href,
    recipeEdit: "/(app)/recipes/[recipeId]/edit" as Href,
    recipeVersion: "/(app)/recipes/[recipeId]/versions/[versionId]" as Href,
    recipes: "/(app)/recipes" as Href,
    settings: "/(app)/settings" as Href,
    shifts: "/(app)/shifts" as Href,
    stations: "/(app)/stations" as Href,
    taskCreate: "/(app)/tasks/new" as Href,
    taskDetail: "/(app)/tasks/[taskId]" as Href,
    taskEdit: "/(app)/tasks/[taskId]/edit" as Href,
    tasks: "/(app)/tasks" as Href,
    myTasks: "/(app)/tasks/mine" as Href,
    notifications: "/(app)/notifications" as Href,
    teamDetail: "/(app)/team/[teamId]" as Href,
    teamRoster: "/(app)/team" as Href,
    venueCreate: "/(app)/venues/create" as Href,
    venueDetail: "/(app)/venues/[id]" as Href,
    venueEdit: "/(app)/venues/[id]/edit" as Href,
    venues: "/(app)/venues" as Href,
  },
  onboarding: {
    organization: "/(onboarding)/organization" as Href,
  },
  public: {
    forgotPassword: "/(public)/forgot-password" as Href,
    login: "/(public)/login" as Href,
    register: "/(public)/register" as Href,
    resetPassword: "/(public)/reset-password" as Href,
    welcome: "/(public)/welcome" as Href,
  },
  root: "/" as Href,
} as const;

export type AppRouteHref =
  | (typeof routes.app)[keyof typeof routes.app]
  | (typeof routes.public)[keyof typeof routes.public]
  | (typeof routes.onboarding)[keyof typeof routes.onboarding]
  | typeof routes.root;
